### ISSUE TITLE
Compatibilty with October 420+

### ISSUE THREAD

**Issue by Nantiee** [phegman/October-CMS-Slick-Slider#10]
Hello, 

The plugin is not working with build 420+.

Thank you :)

**Comment by phegman** [comment]
Thanks for the heads up, seeing the error. Have done a lot of research on how to solve this and haven't found any insight yet. If anybody has insight it would be much appreciated. The error is 
`"Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." on line 423 of /Users/peterhegman/Sites/october/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php`

**Comment by phegman** [comment]
This is fixed in the most recent update!
