### ISSUE TITLE
"count(): Parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by Hessel91** [phegman/October-CMS-Slick-Slider#14]
I get this error after upgrade to php7.2
can you please offer support?

**Comment by phegman** [comment]
This has to do with this change in PHP 7.2 http://php.net/manual/en/migration72.incompatible.php/#migration72.incompatible.warn-on-non-countable-types

I will try and fix in the next few days, or feel free to open up a PR to fix the issue

**Comment by phegman** [comment]
Fixed in 1.1.2
