### ISSUE TITLE
wrong url problem

### ISSUE THREAD

**Issue by pierzo** [phegman/October-CMS-Slick-Slider#21]
Hi, after recent update of OctoberCMS images in my  slider dissapear. I get 404 on my images. It turns out that url to images is wrong. It looks like this
http://domain/theme/theme/storage/app/media/slajdery/slide01.jpg
Problem is in two "theme" in url.

**Comment by tonyraoul** [comment]
Hello pierzo can you please elaborate on this issue, your software version and setup ?

**Comment by pierzo** [comment]
Hi, the problem was with the OctoberCMS, not with your plugin. You can read abut it [here](https://github.com/octobercms/october/pull/4055)

**Comment by tonyraoul** [comment]
Thanks for your reply.
