### ISSUE TITLE
error in update 1.0.14

### ISSUE THREAD

**Issue by plyusninva** [phegman/October-CMS-Slick-Slider#6]
"1.0.14 Update makes it possible to include the slider component within the static-pages plugin by Rainlab"
If include the two slider components and specify different slideshow, the result is displayed two identical slideshow.

**Comment by phegman** [comment]
Hello,

This is actually just a current limitation of the plugin. You can only use one instance of the slider on each page. I would like to change this at some point but don't currently have the time. Pull requests are welcome!
