### ISSUE TITLE
How to implement multiple sliders

### ISSUE THREAD

**Issue by epileftro85** [phegman/October-CMS-Slick-Slider#8]
hi, thanks for this plugin, i want to use it in one page building two different sliders, i've been trying this:
```
{% component 'slider' slide_show_id = 1 %}
{% component 'customName1' %}

{% component 'slider' slide_show_id = 2 %}
{% component 'customName2'  %}
```

with no success

**Comment by phegman** [comment]
Hello,

Unfortunately right now it is not possible to have multiple sliders on the same page. I would like to add this feature at some point, but right now I don't have the time. Pull requests are welcome as I know this feature has been requested before!

**Comment by epileftro85** [comment]
hey thanks for the reply, but finally i did it by creating the second slider in a partial and injecting this one in the parent page... (Y)
