### ISSUE TITLE
Backend Configurations Not Altering Anything On The Front End

### ISSUE THREAD

**Issue by ibanks** [phegman/October-CMS-Slick-Slider#9]
Hello Peter.

I am trying to use your slick slider for an application on my job. The issue I'm having is that any configuration changes I'm making in the settings on the backend admin panel are not changing anything on the front end.

I do not have any JavaScript errors, and my permission settings on the main folders I believe that are involved are:
775 plugins (group: www-data)
775 themes (group: www-data)

The version of jQuery I have is 3.2.1. Bootstrap version is 4.0.0-alpha.6-dist which is the latest. And I have all of the required included files for bootstrap (tether.js and utils.js). No errors are there.

However, I do see that your plugin is still loading jQuery 3.1.1 min after my version is already loaded. I've tried to disable this in the plugin's settings panel, but again the front end is not reading the configurations. Do you have any suggestions?

**Comment by phegman** [comment]
Hello,

Are you working on a live server or a development server. Wondering if you have any caching implemented?

**Comment by ibanks** [comment]
Hello,

This is the first time in a while I've check on the status of this issue. I didn't hear anything for a while and left it alone to focus on other parts of the October CMS project. Your plugin is being used on a development server. There is no caching implemented. Because the response took so long, I've been instructed to actually no use the plugin and just to create our own. Now, as I attempt to uninstall your plugin I am getting an error message that I will create another ticket for.
